services:
  web:
    build: .
    command: otree prodserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      # Database
      DATABASE_URL: postgres://otree:otreepass@db:5432/otree
      # Redis (channels layer)
      REDIS_URL: redis://redis:6379/0
      # oTree admin password
      OTREE_ADMIN_PASSWORD: secret123
    volumes:
      - .:/app  # optional: only if you want hot reload in dev

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: otree
      POSTGRES_USER: otree
      POSTGRES_PASSWORD: otreepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always

volumes:
  postgres_data:
